name: Build

on:
  push:
    branches: [main, master]

env:
  FRONT_END_DOMAIN: ${{ secrets.FRONT_END_DOMAIN }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: bloombar/flask-mongodb-web-app-example:latest
